apiVersion: v1
kind: Secret
metadata:
  name: casarrubios-project.git
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: "git"
  url: "https://github.com/jaruizes/casarrubios-project.git"
