
site_name: applications-manager-service
site_description: Applications Manager Service for Casarrubios Project

nav:
  - Home: index.md

plugins:
  - techdocs-core


# Repository information
repo_url: https://github.com/jaruizes/casarrubios-project
edit_uri: edit/main/project/candidates/backend/services/applications-manager-service

