replicaCount: 1

image:
  repository: ghcr.io/jaruizes/applications/applications-manager-service
  tag: "1.0.0"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

config:
  SERVER_PORT: 8090
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/applications"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: applications
  MINIO_URL: "http://minio:9000"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  OTEL_SERVICE_NAME: "applications-manager-service"
  OTEL_METRICS_EXPORTER: "none"

secrets:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  MINIO_ACCESS_NAME: minioadmin
  MINIO_ACCESS_SECRET: minioadmin

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
