apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: "jaegertracing/jaeger:2.4.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 16686
              name: http
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 14250
              name: model
            - containerPort: 14268
              name: collector
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  type: LoadBalancer
  ports:
    - port: 16686
      targetPort: http
      protocol: TCP
      name: http
    - port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: 14250
      targetPort: model
      protocol: TCP
      name: model
    - port: 14268
      targetPort: collector
      protocol: TCP
      name: collector
  selector:
    app: jaeger
