---
services:
  ### INFRASTRUCTURE SERVICES ###

  postgresql:
    image: postgres:14
    container_name: infrastructure.postgresql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=applications
    volumes:
      - "./postgresql/inventory.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf"

  minio:
    image: quay.io/minio/minio
    container_name: infrastructure.minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: infrastructure.zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
#      EXTRA_ARGS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.20.0.jar=9200:/usr/share/jmx_exporter/zookeeper.yml
#    volumes:
#      - ./jmx-exporter:/usr/share/jmx_exporter/
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 30s
      timeout: 10s
      retries: 5

  broker:
    image: confluentinc/cp-server:7.5.0
    hostname: broker
    container_name: infrastructure.broker
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_JMX_PORT: 9101
#      KAFKA_JMX_HOSTNAME: localhost
#      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
#      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
#      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
#      CONFLUENT_METRICS_ENABLE: 'true'
#      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
#      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.20.0.jar=9200:/usr/share/jmx_exporter/kafka-broker.yml
#    volumes:
#      - ./jmx-exporter:/usr/share/jmx_exporter/
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8090/kafka/v3/clusters" ]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: infrastructure.kafka-ui
    ports:
      - 8001:8001
    depends_on:
      zookeeper:
        condition: service_healthy
      broker:
        condition: service_healthy
    environment:
      SERVER_PORT: 8001
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "broker:29092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "http://schema-registry:8081"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8001" ]
      interval: 30s
      timeout: 10s
      retries: 5

  cdc-service:
    image: quay.io/debezium/connect:3.0
    hostname: connect
    container_name: infrastructure.cdc-service
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: 'broker:29092'
      ADVERTISED_HOST_NAME: connect
      GROUP_ID: debezium-connect-group
      CONFIG_STORAGE_TOPIC: dbz-connect-configs
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_FLUSH_INTERVAL_MS: 10000
      OFFSET_STORAGE_TOPIC: dbz-connect-offsets
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_TOPIC: docker-connect-status
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      ENABLE_DEBEZIUM_SCRIPTING: 'true'
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8083" ]
      interval: 30s
      timeout: 10s
      retries: 5

  cdc-service-init:
    image: curlimages/curl:latest
    container_name: infrastructure.cdc-service-init
    depends_on:
      cdc-service:
        condition: service_healthy
    volumes:
      - ../../project/applications/cdc/connectors/applications-cdc-postgresql-connector.json:/connectors/applications-cdc-postgresql-connector.json
      - ../../project/recruiters/cdc/connectors/recruiters-positions-cdc-connector.json:/connectors/recruiters-positions-cdc-connector.json
      - ./cdc/register-connectors.sh:/register-connectors.sh
    entrypoint: [ "sh", "/register-connectors.sh" ]

  kafka-init:
    image: confluentinc/cp-server:7.5.0
    container_name: infrastructure.kafka-init
    depends_on:
      broker:
        condition: service_healthy
    volumes:
      - ./kafka/init-topics.sh:/init-topics.sh
      - ./kafka/topics-to-create.txt:/topics-to-create.txt
    command: bash /init-topics.sh


  ### -------------------------------------------------------------- ###
  ### "CANDIDATE SIDE" SERVICES ###
  applications-applications-app:
    image: "applications/applications-app:1.0.0"
    container_name: applications.applications-app
    ports:
      - "8081:8081"

  applications-applications-bff:
    image: "applications/applications-bff:1.0.0"
    container_name: applications.applications-bff
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://applications-positions-service:8080
      - APPLICATIONS_BACKEND_URL=http://applications-manager-service:8090

  applications-positions-service:
    image: "applications/positions-service:1.0.0"
    container_name: applications.positions-service
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_started
      broker:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/applications
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=applications
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - NEW-POSITIONS-PUBLISHED_TOPIC=recruiters.new-positions-published
      - SPRING_KAFKA_CONSUMER_GROUP-ID=positions-service


  applications-manager-service:
    image: "applications/applications-manager-service:1.0.0"
    container_name: applications.manager-service
    ports:
      - "8090:8090"
    depends_on:
      postgresql:
        condition: service_started
      minio:
        condition: service_healthy
    environment:
      - SERVER_PORT=8090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/applications
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=applications
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_NAME=minioadmin
      - MINIO_ACCESS_SECRET=minioadmin

### -------------------------------------------------------------- ###
### "RECRUITERS SIDE" SERVICES ###
  recruitment-recruitment-app:
    image: "recruitment/recruitment-app:1.0.0"
    container_name: recruitment.recruitment-app
    ports:
      - "9070:9070"

  recruitment-recruitment-bff:
    image: "recruitment/recruitment-bff:1.0.0"
    container_name: recruitment.recruitment-bff
    ports:
      - "4000:4000"
    environment:
      - POSITIONS_SERVICE_URL=http://recruitment-positions-service:9080
      - APPLICATIONS_SERVICE_URL=http://recruitment-applications-service:9081
      - PORT=4000

  recruitment-positions-service:
    image: "recruitment/positions-manager-service:1.0.0"
    container_name: recruitment.positions-manager-service
    ports:
      - "9080:9080"
    depends_on:
      postgresql:
        condition: service_started
    environment:
      - QUARKUS_HTTP_PORT=9080
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/applications
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_HIBERNATE-ORM_DATABASE_DEFAULT_SCHEMA=recruiters

  recruitment-positions-publisher-service:
    image: "recruitment/new-positions-publisher-service:1.0.0"
    container_name: recruitment.new-positions-publisher-service
    depends_on:
      broker:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    environment:
      - QUARKUS_KAFKA-STREAMS_BOOTSTRAP-SERVERS=broker:29092
      - CDC_RECRUITERS_POSITIONS_TOPIC=cdc.recruiters.positions
      - CDC_RECRUITERS_POSITIONS-REQUIREMENTS_TOPIC=cdc.recruiters.requirements
      - CDC_RECRUITERS_POSITIONS-BENEFITS_TOPIC=cdc.recruiters.benefits
      - CDC_RECRUITERS_POSITIONS-TASK_TOPIC=cdc.recruiters.tasks
      - RECRUITERS_NEW-POSITIONS-PUBLISHED_TOPIC=recruiters.new-positions-published
      - QUARKUS.KAFKA-STREAMS.TOPICS=cdc.recruiters.positions,cdc.recruiters.requirements,cdc.recruiters.benefits,cdc.recruiters.tasks
      - QUARKUS_KAFKA-STREAMS_APPLICATION-ID=quarkus-kafka-streams2

  recruitment-applications-updater-service:
    image: "recruitment/applications-updater-service:1.0.0"
    container_name: recruitment.applications-updater-service
    depends_on:
      postgresql:
        condition: service_started
      broker:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/applications
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_HIBERNATE-ORM_DATABASE_DEFAULT_SCHEMA=recruiters
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - MP_MESSAGING_INCOMING_CDC-APPLICATIONS_TOPIC=cdc.applications.applications

  recruitment-applications-service:
    image: "recruitment/applications-service:1.0.0"
    container_name: recruitment.applications-service
    ports:
      - "9081:9081"
    depends_on:
      postgresql:
        condition: service_started
      broker:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=applications
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_SCHEMA=recruiters
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - KAFKA_INPUT_TOPIC=recruitment.applications-scored
      - KAFKA_CONSUMER_GROUP=applications-service
      - KAFKA_CONSUMER_OFFSET_RESET=earliest
      - LOG_LEVEL=INFO
      - PORT=9081
      - MINIO_URL=minio:9000
      - MINIO_ACCESS_NAME=minioadmin
      - MINIO_ACCESS_SECRET=minioadmin
      - MINIO_BUCKET_NAME=resumes
    restart: unless-stopped

  recruitment-applications-analyzer-service:
    image: "recruitment/applications-analyzer-service:1.0.0"
    container_name: recruitment.applications-analyzer-service
    ports:
      - "9082:9082"
    depends_on:
      postgresql:
        condition: service_started
      broker:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    environment:
      - SERVER_PORT=9082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/applications
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=applications
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_NAME=minioadmin
      - MINIO_ACCESS_SECRET=minioadmin
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - SPRING_AI_OPENAI_API_KEY=${OPENAI_API_KEY}

  recruitment-scoring-service:
    image: "recruitment/scoring-service:1.0.0"
    container_name: recruitment.scoring-service
    depends_on:
      postgresql:
        condition: service_started
      broker:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=applications
      - DB_HOST=postgresql
      - DB_PORT=5432
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - KAFKA_CONSUMER_GROUP=scoring-service
      - KAFKA_CONSUMER_OFFSET_RESET=earliest
      - KAFKA_INPUT_TOPIC=recruitment.applications-analyzed
      - KAFKA_OUTPUT_TOPIC=recruitment.applications-scored
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  minio_data:

networks:
  my_network:
    driver: bridge
