apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaruizes/casarrubios-project.git
    targetRevision: HEAD
    path: platform/k8s/argocd/infrastructure/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
