openapi: 3.1.0
info:
  title: Positions API (Candidates)
  description: |-
    This is the specification for the Positions API. This API is used to manage the positions that candidates can apply
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/positions'
    description: Local server
tags:
  - name: positions
    description: Operations about positions
paths:
    /positions:
      get:
        summary: Find all the open positions
        description: Returns all the open positions for candidates to apply
        operationId: getAllPositions
        tags:
          - positions
        parameters:
          - name: page
            in: query
            description: Page number for pagination (0-based index)
            required: false
            schema:
              type: integer
              format: int32
              default: 0
          - name: size
            in: query
            description: Number of items per page
            required: false
            schema:
              type: integer
              format: int32
              default: 10
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/PaginatedPositionsDTO'
    /positions/{positionId}:
          get:
            summary: Find position by ID
            description: Returns a single position
            operationId: getPositionDetail
            tags:
              - positions
            parameters:
              - name: positionId
                in: path
                description: ID of position to return
                required: true
                schema:
                  type: integer
                  format: int64
            responses:
              '200':
                description: successful operation
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/PositionDetailDTO'
              '400':
                description: Invalid ID supplied
              '404':
                description: Position not found
components:
  schemas:
    PaginatedPositionsDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/PositionDTO'
        totalElements:
          type: integer
          format: int64
          description: Total number of positions available
        totalPages:
          type: integer
          format: int32
          description: Total number of pages
        size:
          type: integer
          format: int32
          description: Number of elements per page
        number:
          type: integer
          format: int32
          description: Current page number
    PositionDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100000
        title:
          type: string
          example: Software Engineer
        description:
          type: string
          example: This position is for a software engineer
    PositionDetailDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100000
        title:
          type: string
          example: Software Engineer
        description:
          type: string
          example: This position is for a software engineer
        requirements:
          type: array
          items:
            $ref: '#/components/schemas/RequirementDTO'
        conditions:
          type: array
          items:
            $ref: '#/components/schemas/ConditionDTO'
    RequirementDTO:
      type: object
      properties:
        description:
          type: string
          example: The candidate must have a degree in computer science
    ConditionDTO:
      type: object
      properties:
        description:
          type: string
          example: The candidate must have a degree in computer science


  
