apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recruitment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaruizes/casarrubios-project.git
    targetRevision: HEAD
    path: platform/k8s/argocd/recruitment/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
