receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318


exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:
  filter/exclusions_kafka_connect_spans:
    traces:
      span:
        - resource.attributes["service.name"] == "kafka-connect" and attributes["span.kind"] == "client"
        - resource.attributes["service.name"] == "kafka-connect" and attributes["span.kind"] == "server"


service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, filter/exclusions_kafka_connect_spans]
      exporters: [otlp/jaeger]
