receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318


exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_mib: 100
    spike_limit_mib: 20

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger]
