# generated by fastapi-codegen:
#   filename:  resources/applications-service-openapi.yaml
#   timestamp: 2025-02-28T10:46:23+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class CandidateDTO(BaseModel):
    name: str = Field(..., description='The name of the candidate', example='John')
    email: str = Field(
        ...,
        description='The email address of the candidate',
        example='john.doe@example.com',
    )
    phone: str = Field(
        ..., description='The phone number of the candidate', example=1234567890
    )


class ApplicationDTO(BaseModel):
    applicationId: int = Field(..., description='The ID of the application', example=1)
    candidate: CandidateDTO
    positionId: int = Field(..., description='The ID of the position', example=1789)
    cvFile: str = Field(
        ...,
        description='Path to the cv stored in the file system',
        example='/path/to/cv.pdf',
    )
    creationDate: str = Field()


class PaginatedApplicationsDTO(BaseModel):
    applications: Optional[List[ApplicationDTO]] = None
    totalElements: Optional[int] = Field(
        None, description='Total number of applications available'
    )
    totalPages: Optional[int] = Field(None, description='Total number of pages')
    size: Optional[int] = Field(None, description='Number of elements per page')
    number: Optional[int] = Field(None, description='Current page number')
