apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  host: "#POSTGRES_HOST#"
  dbname: "casarrubios"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dataloader
spec:
  template:
    spec:
      containers:
        - name: dataloader
          image: ghcr.io/jaruizes/infrastructure/data-loader:1.0.0
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: password
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: username
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: host
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: dbname
      restartPolicy: Never
  backoffLimit: 3

