apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui-tool
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: infrastructure
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/jaruizes/casarrubios-project.git
    targetRevision: HEAD
    path: platform/k8s/manifests/kafka/ui-tool
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
