apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-jaeger
  labels:
    app: {{ .Chart.Name }}-jaeger
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-jaeger
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-jaeger
    spec:
      containers:
        - name: jaeger
          image: "{{ .Values.jaeger.image.repository }}:{{ .Values.jaeger.image.tag }}"
          imagePullPolicy: {{ .Values.jaeger.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.jaeger.service.port }}
              name: http
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 14250
              name: model
            - containerPort: 14268
              name: collector
          env:
            {{- range $key, $value := .Values.jaeger.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.jaeger.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-jaeger
  labels:
    app: {{ .Chart.Name }}-jaeger
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Chart.Name }}
spec:
  type: {{ .Values.jaeger.service.type }}
  ports:
    - port: {{ .Values.jaeger.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: 14250
      targetPort: model
      protocol: TCP
      name: model
    - port: 14268
      targetPort: collector
      protocol: TCP
      name: collector
  selector:
    app: {{ .Chart.Name }}-jaeger
{{- if .Values.jaeger.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-jaeger
  labels:
    app: {{ .Chart.Name }}-jaeger
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Chart.Name }}
spec:
  ingressClassName: {{ .Values.jaeger.ingress.className }}
  rules:
    - host: {{ .Values.jaeger.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-jaeger
                port:
                  number: {{ .Values.jaeger.service.port }}
{{- end }}
