apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-otel-collector-config
  labels:
    app: {{ .Release.Name }}-otel-collector
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  otel-collector-config.yaml: |
    {{- toYaml .Values.otelcollector.config | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-otel-collector
  labels:
    app: {{ .Release.Name }}-otel-collector
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-otel-collector
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-otel-collector
    spec:
      containers:
        - name: otel-collector
          image: "{{ .Values.otelcollector.image.repository }}:{{ .Values.otelcollector.image.tag }}"
          imagePullPolicy: {{ .Values.otelcollector.image.pullPolicy }}
          command:
            - /otelcol
            - --config=/etc/otel-collector-config.yaml
          ports:
            - containerPort: {{ .Values.otelcollector.service.ports.grpc }}
              name: grpc
            - containerPort: {{ .Values.otelcollector.service.ports.http }}
              name: http
            - containerPort: {{ .Values.otelcollector.service.ports.health }}
              name: health
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
          resources:
            {{- toYaml .Values.otelcollector.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: otel-collector-config
          configMap:
            name: {{ .Release.Name }}-otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-otel-collector
  labels:
    app: {{ .Release.Name }}-otel-collector
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.otelcollector.service.type }}
  ports:
    - port: {{ .Values.otelcollector.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.otelcollector.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.otelcollector.service.ports.health }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    app: {{ .Release.Name }}-otel-collector
