replicaCount: 1

image:
  repository: ghcr.io/jaruizes/applications/applications-bff
  tag: "1.0.0"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

config:
  PORT: 3000
  BACKEND_URL: "http://applications-positions-service:8080"
  APPLICATIONS_BACKEND_URL: "http://applications-manager-service:8090"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"


resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
