name: (Applications) Applications Manager Service

on:
  workflow_dispatch:
  push:
    paths:
      - 'project/candidates/backend/services/applications-manager-service/**'
  pull_request:
    paths:
      - 'project/candidates/backend/services/applications-manager-service/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/spring-service.yml
    with:
      domain: applications
      service-name: applications-manager-service
      service-path: project/candidates/backend/services/applications-manager-service
    secrets: inherit
