name: (Applications) BFF

on:
  workflow_dispatch:
  push:
    paths:
      - 'project/applications/frontend/applications-bff/**'
  pull_request:
    paths:
      - 'project/applications/frontend/applications-bff/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/node-application.yml
    with:
      domain: applications
      service-name: applications-bff
      service-path: project/applications/frontend/applications-bff
    secrets: inherit
