name: (Applications) Positions Service

on:
  workflow_dispatch:
  push:
    paths:
      - 'project/applications/backend/services/positions-service/**'
  pull_request:
    paths:
      - 'project/applications/backend/services/positions-service/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/spring-service.yml
    with:
      image-name: applications/positions-service
      service-path: project/applications/backend/services/applications-manager-service
