name: Build Applications Manager Service

on:
  workflow_dispatch:
  push:
    paths:
      - 'project/applications/backend/services/applications-manager-service/**'
  pull_request:
    paths:
      - 'project/applications/backend/services/applications-manager-service/**'

jobs:
  build:
    uses: ./.github/workflows/spring-service.yml
    with:
      image-name: applications/applications-manager-service
      service-path: project/applications/backend/services/applications-manager-service
