name: (Applications) Angular Application

on:
  workflow_dispatch:
  push:
    paths:
      - 'project/candidates/frontend/candidates-app/**'
  pull_request:
    paths:
      - 'project/candidates/frontend/candidates-app/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/node-application.yml
    with:
      domain: applications
      service-name: applications-app
      service-path: project/applications/frontend/candidates-app
    secrets: inherit
