name: (Infrastructure) CDC Service

on:
  workflow_dispatch:
  push:
    paths:
      - 'platform/local/debezium-strimzi/**'
  pull_request:
    paths:
      - 'platform/local/debezium-strimzi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform/local/debezium-strimzi
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/infrastructure/cdc-service:1.0.0 --build-arg DEBEZIUM_CONNECTOR_VERSION=3.1.0.Final --build-arg STRIMZI_VERSION=latest-kafka-3.9.0 .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/infrastructure/cdc-service:1.0.0
  
