name: (Base) Quarkus Services

on:
  workflow_call:
    inputs:
      service-path:
        required: true
        type: string
      image-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    defaults:
      run:
        working-directory: ${{ inputs.service-path }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Package application (without tests)
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -f src/main/docker/Dockerfile.jvm -t ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:${{ steps.extract_version.outputs.VERSION }} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:${{ steps.extract_version.outputs.VERSION }}
