name: (Base) Quarkus Services

on:
  workflow_call:
    inputs:
      service-path:
        required: true
        type: string
      domain:
        required: true
        type: string
      service-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    defaults:
      run:
        working-directory: ${{ inputs.service-path }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build, analysis and package
        run: ./mvnw clean package -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ inputs.service-name }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=casarrubios-project -DskipPitest

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -f src/main/docker/Dockerfile.jvm -t ghcr.io/${{ github.repository_owner }}/${{ inputs.domain }}/${{ inputs.service-name }}:${{ steps.extract_version.outputs.VERSION }} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ inputs.domain }}/${{ inputs.service-name }}:${{ steps.extract_version.outputs.VERSION }}
