name: (Recruitment) BFF

on:
  workflow_dispatch:
  push:
    paths:
      - 'project/recruitment/frontend/recruitment-bff/**'
  pull_request:
    paths:
      - 'project/recruitment/frontend/recruitment-bff/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/node-application.yml
    with:
      domain: recruitment
      service-name: recruitment-bff
      service-path: project/recruitment/frontend/recruitment-bff
    secrets: inherit
