name: (Recruitment) Applications Updater Service

on:
  workflow_dispatch:
  push:
    paths:
      - 'project/recruiters/backend/services/applications-updater/**'
  pull_request:
    paths:
      - 'project/recruiters/backend/services/applications-updater/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/quarkus-service.yml
    with:
      domain: recruitment
      service-name: applications-updater-service
      service-path: project/recruiters/backend/services/applications-updater
