name: (Recruitment) Applications Service

on:
  workflow_dispatch:
  push:
    paths:
      - 'project/recruitment/backend/services/applications-service/**'
  pull_request:
    paths:
      - 'project/recruitment/backend/services/applications-service/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/python-service.yml
    with:
      domain: recruitment
      service-name: applications-service
      service-path: project/recruitment/backend/services/applications-service
    secrets: inherit
