name: (Recruitment) Resume Analyzer Service

on:
  workflow_dispatch:
  push:
    paths:
      - 'project/recruiters/backend/services/resume-analyzer-service/**'
  pull_request:
    paths:
      - 'project/recruiters/backend/services/resume-analyzer-service/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/spring-service.yml
    with:
      image-name: recruitment/applications-analyzer-service
      service-path: project/recruiters/backend/services/resume-analyzer-service
