name: (Recruitment) Insights Service

on:
  workflow_dispatch:
  push:
    paths:
      - 'project/recruiters/backend/services/insights-service/**'
  pull_request:
    paths:
      - 'project/recruiters/backend/services/insights-service/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/quarkus-service.yml
    with:
      domain: recruitment
      service-name: insights-service
      service-path: project/recruiters/backend/services/insights-service
    secrets: inherit
