name: (Recruitment) Positions Manager Service

on:
  workflow_dispatch:
  push:
    paths:
      - 'project/applications/backend/services/positions-service/**'
  pull_request:
    paths:
      - 'project/applications/backend/services/positions-service/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/quarkus-service.yml
    with:
      image-name: recruitment/positions-manager-service
      service-path: project/recruiters/backend/services/positions-manager-service
