name: (Recruitment) New Positions Publisher Service

on:
  workflow_dispatch:
  push:
    paths:
      - 'project/recruitment/backend/services/new-positions-publisher/**'
  pull_request:
    paths:
      - 'project/recruitment/backend/services/new-positions-publisher/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/quarkus-service.yml
    with:
      domain: recruitment
      service-name: new-positions-publisher-service
      service-path: project/recruitment/backend/services/new-positions-publisher
    secrets: inherit
